services:
  ordersystem:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../cmd/ordersystem/.env
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_catalog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
