version: '3.8'

services:
  ordersystem:
    container_name: catalogo
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../cmd/ordersystem/.env
    networks:
      - rede_interna

networks:
  rede_interna:
    external: true
