version: "3.8"

services:
  httpserver:
    container_name: httpserver
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../cmd/ordersystem/.env
    networks:
      - rede_interna

  grpcserver:
    container_name: grpcserver
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile.grpc
    ports:
      - "50051:50051"
    env_file:
      - ../cmd/ordersystem/.env
    networks:
      - rede_interna

networks:
  rede_interna:
    external: true
