// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: catalog/internal/infra/grpc/protofiles/comboname.proto

package comboname

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CreateComboNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateComboNameRequest) Reset() {
	*x = CreateComboNameRequest{}
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateComboNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateComboNameRequest) ProtoMessage() {}

func (x *CreateComboNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateComboNameRequest.ProtoReflect.Descriptor instead.
func (*CreateComboNameRequest) Descriptor() ([]byte, []int) {
	return file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescGZIP(), []int{2}
}

func (x *CreateComboNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateComboNameRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type UpdateComboNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateComboNameRequest) Reset() {
	*x = UpdateComboNameRequest{}
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateComboNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateComboNameRequest) ProtoMessage() {}

func (x *UpdateComboNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateComboNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateComboNameRequest) Descriptor() ([]byte, []int) {
	return file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateComboNameRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateComboNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateComboNameRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type DisableComboNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableComboNameRequest) Reset() {
	*x = DisableComboNameRequest{}
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableComboNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableComboNameRequest) ProtoMessage() {}

func (x *DisableComboNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableComboNameRequest.ProtoReflect.Descriptor instead.
func (*DisableComboNameRequest) Descriptor() ([]byte, []int) {
	return file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescGZIP(), []int{4}
}

func (x *DisableComboNameRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ComboNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ComboNameUuid string                 `protobuf:"bytes,4,opt,name=combo_name_uuid,json=comboNameUuid,proto3" json:"combo_name_uuid,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,5,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComboNameResponse) Reset() {
	*x = ComboNameResponse{}
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComboNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComboNameResponse) ProtoMessage() {}

func (x *ComboNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComboNameResponse.ProtoReflect.Descriptor instead.
func (*ComboNameResponse) Descriptor() ([]byte, []int) {
	return file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescGZIP(), []int{5}
}

func (x *ComboNameResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ComboNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComboNameResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ComboNameResponse) GetComboNameUuid() string {
	if x != nil {
		return x.ComboNameUuid
	}
	return ""
}

func (x *ComboNameResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Combos        []*ComboNameResponse   `protobuf:"bytes,1,rep,name=combos,proto3" json:"combos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllResponse) GetCombos() []*ComboNameResponse {
	if x != nil {
		return x.Combos
	}
	return nil
}

func (x *GetAllResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DisableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableResponse) Reset() {
	*x = DisableResponse{}
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableResponse) ProtoMessage() {}

func (x *DisableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableResponse.ProtoReflect.Descriptor instead.
func (*DisableResponse) Descriptor() ([]byte, []int) {
	return file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescGZIP(), []int{7}
}

func (x *DisableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_catalog_internal_infra_grpc_protofiles_comboname_proto protoreflect.FileDescriptor

const file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDesc = "" +
	"\n" +
	"6catalog/internal/infra/grpc/protofiles/comboname.proto\x12\tcomboname\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"9\n" +
	"\rGetAllRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"H\n" +
	"\x16CreateComboNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"X\n" +
	"\x16UpdateComboNameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\")\n" +
	"\x17DisableComboNameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9e\x01\n" +
	"\x11ComboNameResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12&\n" +
	"\x0fcombo_name_uuid\x18\x04 \x01(\tR\rcomboNameUuid\x12!\n" +
	"\fis_available\x18\x05 \x01(\bR\visAvailable\"\\\n" +
	"\x0eGetAllResponse\x124\n" +
	"\x06combos\x18\x01 \x03(\v2\x1c.comboname.ComboNameResponseR\x06combos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"+\n" +
	"\x0fDisableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf6\x02\n" +
	"\x10ComboNameService\x12B\n" +
	"\aGetByID\x12\x19.comboname.GetByIDRequest\x1a\x1c.comboname.ComboNameResponse\x12=\n" +
	"\x06GetAll\x12\x18.comboname.GetAllRequest\x1a\x19.comboname.GetAllResponse\x12I\n" +
	"\x06Create\x12!.comboname.CreateComboNameRequest\x1a\x1c.comboname.ComboNameResponse\x12I\n" +
	"\x06Update\x12!.comboname.UpdateComboNameRequest\x1a\x1c.comboname.ComboNameResponse\x12I\n" +
	"\aDisable\x12\".comboname.DisableComboNameRequest\x1a\x1a.comboname.DisableResponseB*Z(catalog/internal/infra/grpc/pb;combonameb\x06proto3"

var (
	file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescOnce sync.Once
	file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescData []byte
)

func file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescGZIP() []byte {
	file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescOnce.Do(func() {
		file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDesc), len(file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDesc)))
	})
	return file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDescData
}

var file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_catalog_internal_infra_grpc_protofiles_comboname_proto_goTypes = []any{
	(*GetByIDRequest)(nil),          // 0: comboname.GetByIDRequest
	(*GetAllRequest)(nil),           // 1: comboname.GetAllRequest
	(*CreateComboNameRequest)(nil),  // 2: comboname.CreateComboNameRequest
	(*UpdateComboNameRequest)(nil),  // 3: comboname.UpdateComboNameRequest
	(*DisableComboNameRequest)(nil), // 4: comboname.DisableComboNameRequest
	(*ComboNameResponse)(nil),       // 5: comboname.ComboNameResponse
	(*GetAllResponse)(nil),          // 6: comboname.GetAllResponse
	(*DisableResponse)(nil),         // 7: comboname.DisableResponse
}
var file_catalog_internal_infra_grpc_protofiles_comboname_proto_depIdxs = []int32{
	5, // 0: comboname.GetAllResponse.combos:type_name -> comboname.ComboNameResponse
	0, // 1: comboname.ComboNameService.GetByID:input_type -> comboname.GetByIDRequest
	1, // 2: comboname.ComboNameService.GetAll:input_type -> comboname.GetAllRequest
	2, // 3: comboname.ComboNameService.Create:input_type -> comboname.CreateComboNameRequest
	3, // 4: comboname.ComboNameService.Update:input_type -> comboname.UpdateComboNameRequest
	4, // 5: comboname.ComboNameService.Disable:input_type -> comboname.DisableComboNameRequest
	5, // 6: comboname.ComboNameService.GetByID:output_type -> comboname.ComboNameResponse
	6, // 7: comboname.ComboNameService.GetAll:output_type -> comboname.GetAllResponse
	5, // 8: comboname.ComboNameService.Create:output_type -> comboname.ComboNameResponse
	5, // 9: comboname.ComboNameService.Update:output_type -> comboname.ComboNameResponse
	7, // 10: comboname.ComboNameService.Disable:output_type -> comboname.DisableResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_catalog_internal_infra_grpc_protofiles_comboname_proto_init() }
func file_catalog_internal_infra_grpc_protofiles_comboname_proto_init() {
	if File_catalog_internal_infra_grpc_protofiles_comboname_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDesc), len(file_catalog_internal_infra_grpc_protofiles_comboname_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_internal_infra_grpc_protofiles_comboname_proto_goTypes,
		DependencyIndexes: file_catalog_internal_infra_grpc_protofiles_comboname_proto_depIdxs,
		MessageInfos:      file_catalog_internal_infra_grpc_protofiles_comboname_proto_msgTypes,
	}.Build()
	File_catalog_internal_infra_grpc_protofiles_comboname_proto = out.File
	file_catalog_internal_infra_grpc_protofiles_comboname_proto_goTypes = nil
	file_catalog_internal_infra_grpc_protofiles_comboname_proto_depIdxs = nil
}
